### ISSUE TITLE
Whitespaces and list items are moving to the right.

### ISSUE THREAD

**Issue by maxomaniak** [MrSaints/Morphist#6]
To solve it open the file animate.css
In .morphist > .animated you should add position: absolute;
And in #js-rotating you should add padding:0;

**Comment by MrSaints** [comment]
Hey @maxomaniak,

Can you provide more details about this problem?

Perhaps a fiddle.

Thanks!

**Comment by maxomaniak** [comment]
Hey @MrSaints,

I couldn't reproduce it in JSFiddle, but here's a temporary url.
http://www.communicationcentre.nl/v2/issue/

Without adding the two lines of css in animate.css every <li> will just stack to the right.

**Comment by MrSaints** [comment]
The 2 problems you have found appears to be related. I'll look further.

**Comment by MrSaints** [comment]
Closing this issue. We'll continue the discussion in #7.
