### ISSUE TITLE
Doesn't keep looping like morphext. 

### ISSUE THREAD

**Issue by maxomaniak** [MrSaints/Morphist#7]
Doesn't keep looping like morphext does. Stops after the last list item.

**Comment by MrSaints** [comment]
Hey @maxomaniak,

Thanks for reporting this. Do you have a live demo I could look into?

**Comment by maxomaniak** [comment]
Hey Ian,

Thanks for helping me out!
http://www.communicationcentre.nl/v2/

Regards,

Max

On Tue, Mar 22, 2016 at 12:18 PM, Ian L. <notifications@github.com> wrote:

> Hey @maxomaniak <https://github.com/maxomaniak>,
>
> Thanks for reporting this. Do you have a live demo I could look into?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MrSaints/Morphist/issues/7#issuecomment-199765761>
>



-- 
Met vriendelijke groet,

Max Seelig
PKDB <https://www.facebook.com/teampkdb>

**Comment by MrSaints** [comment]
Apologies for the late response. I finally found some time to look into it.

As I've mentioned in the other issue (#6), the problems you have appear to be related. And they appear to be caused by the animation classes not being reset. I'm somewhat convinced that it has to do with some other plugins on your website.

Could you try removing some of your other plugins (e.g. `dmenu`), and letting me know if it has any sort of impact?

**Comment by maxomaniak** [comment]
Ian,

Sorry for the late response, got some days off of work and haven't checked
my mail. I've tried removing all other .js plugins but that didn't work
out.

On Sat, Mar 26, 2016 at 1:40 PM, Ian L. <notifications@github.com> wrote:

> Apologies for the late response. I finally found some time to look into it.
>
> As I've mentioned in the other issue (#6
> <https://github.com/MrSaints/Morphist/issues/6>), the problems you have
> appear to be related. And they appear to be caused by the animation classes
> not being reset. I'm somewhat convinced that it has to do with some other
> plugins on your website.
>
> Could you try removing some of your other plugins (e.g. dmenu), and
> letting me know if it has any sort of impact?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MrSaints/Morphist/issues/7#issuecomment-201805214>
>



-- 
Met vriendelijke groet,

Max Seelig
PKDB <https://www.facebook.com/teampkdb>

**Comment by MrSaints** [comment]
No worries @maxomaniak. 

If it's no trouble, can you give https://github.com/MrSaints/Morphist/releases/tag/3.0.0 a try?

**Comment by maxomaniak** [comment]
Just tried it, still not working. I noticed that the classes "animated
mis-in bounceInLeft mis-out bounceOutRight" won't be removed after the
animation.

On Wed, Mar 30, 2016 at 11:16 AM, Ian L. <notifications@github.com> wrote:

> No worries @maxomaniak <https://github.com/maxomaniak>.
>
> If it's no trouble, can you give
> https://github.com/MrSaints/Morphist/releases/tag/3.0.0 a try?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MrSaints/Morphist/issues/7#issuecomment-203339443>
>



-- 
Met vriendelijke groet,

Max Seelig
PKDB <https://www.facebook.com/teampkdb>

**Comment by MrSaints** [comment]
@maxomaniak Yea, that's very unusual. Apologies for the tardy response. I haven't had a chance to look into it thoroughly.

**Comment by MrSaints** [comment]
@maxomaniak Okay, I managed to isolate the problem. It appears that _jQuery UI effect_ is messing with the standard behaviour for several methods. If you remove `jquery.easings.min.js`, it should work as expected. However, if you do want to keep it, I suggest upgrading to the latest _jQuery UI effect (easings)_ as I believe this is a bug in their old code.

Let me know how it goes :) And once again, apologies for the delayed response.

**Comment by maxomaniak** [comment]
Ian, I've upgraded jquery.easings.min.js to version 1.3 and the problem
seems to be solved! Thank you very much!

On Mon, Apr 4, 2016 at 12:10 AM, Ian L. <notifications@github.com> wrote:

> @maxomaniak <https://github.com/maxomaniak> Okay, I managed to isolate
> the problem. It appears that *jQuery UI effect* is messing with the
> standard behaviour for several methods. If you remove
> jquery.easings.min.js, it should work as expected. However, if you do
> want to keep it, I suggest upgrading to the latest *jQuery UI effect
> (easings)* as I believe this is a bug in their old code.
>
> Let me know how it goes :) And once again, apologies for the delayed
> response.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MrSaints/Morphist/issues/7#issuecomment-205062701>
>



-- 
Met vriendelijke groet,

Max Seelig
PKDB <https://www.facebook.com/teampkdb>
