### ISSUE TITLE
animateOut doesn't fire (randomly)

### ISSUE THREAD

**Issue by Netherland** [MrSaints/Morphist#9]
The exit animation sometimes doesn't fire, it is rather random (Spend 5 minutes trying to record that 5 second loop).
It does seem like it is caused by having a too low delay (1000ms)

![Example](https://i.gyazo.com/bd06abd1c8feb7e436f1d3b6eb2756cf.gif)

Settings used:
`    animateIn: "fadeIn",
    animateOut: "fadeOut",
    speed: 1000,`

**Comment by MrSaints** [comment]
That's interesting. May I know what browser you are on, and the version? I'm unable to replicate it (with 500ms timeout).

**Comment by Netherland** [comment]
Chrome 49.0.2623.87m. Just a side note;  also tried on FireFox 45.0.1, it works fine there, but the first time I tried it out it didn't fire animateOut on the last element. Can't reproduce that either, but might be worth mentioning.

**Comment by MrSaints** [comment]
I've tested it on that version to no avail. Nevertheless, thank you for reporting (and recording) it :)

I'll keep this opened in case someone else is facing the same problem. But hopefully, [v3.0.0](https://github.com/MrSaints/Morphist/releases/tag/3.0.0) will not be affected by this.

**Comment by Netherland** [comment]
Tested it with Chrome 49.0.2623.87m, seems to be working perfect (on v3.0.0).
Great job, thank you.
